-- Auto-generated by scripts/generate_lots.py. Do not edit by hand.
-- One rule per (lot, permit_id, day_range, time_window) combination.
-- Applied uniformly to every lot of a given permit category.
DROP TABLE IF EXISTS parking_rules;

CREATE TABLE parking_rules (
    lot_id VARCHAR(50),
    permit_id VARCHAR(50),
    day_of_week VARCHAR(50),
    start_time TIME,
    end_time TIME,
    is_allowed BOOLEAN,
    
    CONSTRAINT fk_lot 
        FOREIGN KEY (lot_id) 
        REFERENCES parking_lots(lot_id)
        ON DELETE CASCADE ON UPDATE CASCADE
);

INSERT INTO parking_rules
    (lot_id, permit_id, day_of_week, start_time, end_time, is_allowed)
SELECT l.lot_id, r.permit_id, r.day_of_week, r.start_time, r.end_time, TRUE
FROM parking_lots l
JOIN (
    SELECT 'Faculty' AS zone, 'FS' AS permit_id, 'Mon,Tue,Wed,Thu,Fri' AS day_of_week, '07:00:00' AS start_time, '17:00:00' AS end_time
    UNION ALL
    SELECT 'Faculty' AS zone, 'FS' AS permit_id, 'Sat,Sun' AS day_of_week, '00:00:00' AS start_time, '23:59:59' AS end_time
    UNION ALL
    SELECT 'Faculty' AS zone, 'FR' AS permit_id, 'Mon,Tue,Wed,Thu,Fri' AS day_of_week, '07:00:00' AS start_time, '17:00:00' AS end_time
    UNION ALL
    SELECT 'Faculty' AS zone, 'CB' AS permit_id, 'Mon,Tue,Wed,Thu,Fri' AS day_of_week, '17:00:00' AS start_time, '23:59:59' AS end_time
    UNION ALL
    SELECT 'Faculty' AS zone, 'CR' AS permit_id, 'Mon,Tue,Wed,Thu,Fri' AS day_of_week, '17:00:00' AS start_time, '23:59:59' AS end_time
    UNION ALL
    SELECT 'Commuter Blue' AS zone, 'CB' AS permit_id, 'Mon,Tue,Wed,Thu,Fri' AS day_of_week, '07:00:00' AS start_time, '17:00:00' AS end_time
    UNION ALL
    SELECT 'Commuter Blue' AS zone, 'FS' AS permit_id, 'Mon,Tue,Wed,Thu,Fri' AS day_of_week, '07:00:00' AS start_time, '17:00:00' AS end_time
    UNION ALL
    SELECT 'Commuter Blue' AS zone, 'CB' AS permit_id, 'Sat,Sun' AS day_of_week, '00:00:00' AS start_time, '23:59:59' AS end_time
    UNION ALL
    SELECT 'Commuter Blue' AS zone, 'CR' AS permit_id, 'Sat,Sun' AS day_of_week, '00:00:00' AS start_time, '23:59:59' AS end_time
    UNION ALL
    SELECT 'Commuter Red' AS zone, 'CR' AS permit_id, 'Mon,Tue,Wed,Thu,Fri' AS day_of_week, '07:00:00' AS start_time, '19:00:00' AS end_time
    UNION ALL
    SELECT 'Commuter Red' AS zone, 'FS' AS permit_id, 'Mon,Tue,Wed,Thu,Fri' AS day_of_week, '07:00:00' AS start_time, '19:00:00' AS end_time
    UNION ALL
    SELECT 'Commuter Red' AS zone, 'CR' AS permit_id, 'Sat,Sun' AS day_of_week, '00:00:00' AS start_time, '23:59:59' AS end_time
    UNION ALL
    SELECT 'Commuter Red' AS zone, 'CB' AS permit_id, 'Sat,Sun' AS day_of_week, '00:00:00' AS start_time, '23:59:59' AS end_time
    UNION ALL
    SELECT 'Campus Walk' AS zone, 'CW' AS permit_id, 'Mon,Tue,Wed,Thu,Fri,Sat,Sun' AS day_of_week, '00:00:00' AS start_time, '23:59:59' AS end_time
    UNION ALL
    SELECT 'Residential East' AS zone, 'RE' AS permit_id, 'Mon,Tue,Wed,Thu,Fri,Sat,Sun' AS day_of_week, '00:00:00' AS start_time, '23:59:59' AS end_time
    UNION ALL
    SELECT 'Residential East' AS zone, 'FS' AS permit_id, 'Mon,Tue,Wed,Thu,Fri' AS day_of_week, '17:00:00' AS start_time, '23:59:59' AS end_time
    UNION ALL
    SELECT 'Residential Central' AS zone, 'RC' AS permit_id, 'Mon,Tue,Wed,Thu,Fri,Sat,Sun' AS day_of_week, '00:00:00' AS start_time, '23:59:59' AS end_time
    UNION ALL
    SELECT 'Residential Central' AS zone, 'FS' AS permit_id, 'Mon,Tue,Wed,Thu,Fri' AS day_of_week, '17:00:00' AS start_time, '23:59:59' AS end_time
    UNION ALL
    SELECT 'Residential Northwest' AS zone, 'RNW' AS permit_id, 'Mon,Tue,Wed,Thu,Fri,Sat,Sun' AS day_of_week, '00:00:00' AS start_time, '23:59:59' AS end_time
    UNION ALL
    SELECT 'Residential Northwest' AS zone, 'CB' AS permit_id, 'Sat,Sun' AS day_of_week, '00:00:00' AS start_time, '23:59:59' AS end_time
    UNION ALL
    SELECT 'Residential South' AS zone, 'RS' AS permit_id, 'Mon,Tue,Wed,Thu,Fri,Sat,Sun' AS day_of_week, '00:00:00' AS start_time, '23:59:59' AS end_time
    UNION ALL
    SELECT 'Residential South' AS zone, 'FS' AS permit_id, 'Mon,Tue,Wed,Thu,Fri' AS day_of_week, '17:00:00' AS start_time, '23:59:59' AS end_time
    UNION ALL
    SELECT 'Visitor' AS zone, 'VSD' AS permit_id, 'Mon,Tue,Wed,Thu,Fri' AS day_of_week, '07:00:00' AS start_time, '17:00:00' AS end_time
    UNION ALL
    SELECT 'Visitor' AS zone, 'VSM' AS permit_id, 'Mon,Tue,Wed,Thu,Fri' AS day_of_week, '07:00:00' AS start_time, '17:00:00' AS end_time
    UNION ALL
    SELECT 'Visitor' AS zone, 'VSY' AS permit_id, 'Mon,Tue,Wed,Thu,Fri' AS day_of_week, '07:00:00' AS start_time, '17:00:00' AS end_time
    UNION ALL
    SELECT 'Visitor' AS zone, 'VSD' AS permit_id, 'Sat,Sun' AS day_of_week, '00:00:00' AS start_time, '23:59:59' AS end_time
    UNION ALL
    SELECT 'Visitor' AS zone, 'VSM' AS permit_id, 'Sat,Sun' AS day_of_week, '00:00:00' AS start_time, '23:59:59' AS end_time
    UNION ALL
    SELECT 'Visitor' AS zone, 'VSY' AS permit_id, 'Sat,Sun' AS day_of_week, '00:00:00' AS start_time, '23:59:59' AS end_time
) r ON r.zone = l.zone;